version: '3.2'

services:
  hbase-master:
    image: tlm/hbase-master:1.0.0-hbase0.98.8
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: "16010"
    env_file:
      - ./hbase.env

  hbase-regionserver-1:
    image: tlm/hbase-regionserver:1.0.0-hbase0.98.8
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver-1

  hbase-regionserver-2:
    image: tlm/hbase-regionserver:1.0.0-hbase0.98.8
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver-2

  hbase-regionserver-3:
    image: tlm/hbase-regionserver:1.0.0-hbase0.98.8
    networks:
      - hbase
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver-3

networks:
  hbase:
    external:
      name: hbase
